### ISSUE TITLE
fab skeletonize fails

### ISSUE THREAD

**Issue by tdhopper** [DamnedFacts/flask-boilerplate#2]
`fab skeletonize` fails to patch base_t.html for me: 

```
tdhopper@~/repos/flask-boilerplate (confessions) [master*] $ fab skeletonize
[user@remotehost] Executing task 'skeletonize'
Skeletonizing the project directory...
Installing skeleton HTML5 Boilerplate.
Patching the base template.
Traceback (most recent call last):
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/fabric/tasks.py", line 299, in execute
    multiprocessing
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/fabric/tasks.py", line 198, in _execute
    return task.run(*args, **kwargs)
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/tdhopper/repos/flask-boilerplate/fabfile.py", line 142, in skeletonize
    sh.patch(strip=0, _in=template_patch)
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/sh.py", line 1021, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/sh.py", line 486, in __init__
    self.wait()
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/tdhopper/anaconda/envs/confessions/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1:

  RAN: '/usr/bin/patch --strip=0'

  STDOUT:
patching file base_t.html
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 102.
Hunk #3 FAILED at 126.
3 out of 3 hunks FAILED -- saving rejects to file base_t.html.rej


  STDERR:
```

**Comment by tdhopper** [comment]
[This line](https://github.com/DamnedFacts/flask-boilerplate/blob/75499f37d49d171a995c407746942b59d8c7a018/fabfile.py#L132) updates Skeleton to a breaking version
